services:

  milestone_flow_db:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FLOW_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${FLOW_DB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/flow_db:/data/db
      - ./scripts/flow-db-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - common-net

  milestone_flow_test_db:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FLOW_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${FLOW_DB_ROOT_PASSWORD}
    command: mongod --port 27018
    ports:
      - "27018:27018"
    volumes:
      - ./db_data/flow_test_db:/data/db
      - ./scripts/flow-db-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - common-net

  milestone_postgres:
    container_name: milestone_postgres
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/game_engine_db:/var/lib/postgresql/data
      - ./config/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - common-net

networks:
  common-net: { }