services:

  milestone_flow_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FLOW_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${FLOW_DB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/flow_db:/data/db
      - ./scripts/flow-db-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro