services:

  milestone_core:
    image: public.ecr.aws/h4j3w3q7/milestone-test:latest
    ports:
      - "80:3333"
    depends_on:
      - milestone_flow_db
    env_file:
      - .env
    networks:
      - common-net

  milestone_flow_db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FLOW_DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${FLOW_DB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./db_data/flow_db:/data/db
      - ./flow-db-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - common-net

networks:
  common-net: { }